name: Deployment

on:
  push:
    branches: [main]
    # branches: [develop]

env:
  NODE_VERSION: 20.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  db:
    name: âš™ï¸ Setup database
    runs-on: ubuntu-latest
    environment: Production
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.SUPABASE_GITHUB_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.SUPABASE_GOOGLE_CLIENT_SECRET }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ’¾ Wait for backup to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: ğŸ’¾ Backup
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: ğŸ”¨ Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: âš¡ Setup Supabase CLI
        uses: supabase/setup-cli@v1

      # - name: ğŸ”— Link
      #   run: pnpm run db:link -- --db-url $SUPABASE_DB_URL

      - name: ğŸ“¦ Migrate
        run: pnpm run db:migrate:deploy -- --db-url $SUPABASE_DB_URL

  web:
    name: ğŸš€ Deploy web
    runs-on: ubuntu-latest
    environment: Production
    needs: db
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¨ Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ”¼ Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: ğŸ’ª Pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ“¦ Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ’¨ Deploy!
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  sync:
    name: ğŸš€ Deploy sync
    runs-on: ubuntu-latest
    environment: Production
    needs: db

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”¨ Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: ğŸ’¨ Fly!
        run: flyctl deploy --remote-only -c ./provision/prod/sync/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
