name: Deployment

on:
  push:
    # branches: [main]
    branches: [develop]

env:
  NODE_VERSION: 20.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  db:
    name: âš™ï¸ Setup database
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”¨ Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: âš¡ Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: ğŸ”— Link
        run: pnpm run db:link -- --project-ref $SUPABASE_PROJECT_ID

      - name: ğŸ“¦ Migrate
        run: pnpm run db:migrate:deploy

  web:
    name: ğŸš€ Deploy web
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”¨ Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ”¼ Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: ğŸ’ª Pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ“¦ Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ’¨ Deploy!
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  # deploy:
  #   name: ğŸš€ Deploy
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #     - name: âœ… Checkout code
  #       uses: actions/checkout@v3

  #     - name: ğŸ”¨ Setup Fly
  #       uses: superfly/flyctl-actions/setup-flyctl@master

  #     - name: ğŸ’¨ Fly!
  #       run: flyctl deploy --remote-only --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
