name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-lint:
    name: ğŸ§© Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ¬ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ğŸ”¨ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: ğŸ”Œ Install
        run: pnpm install

      - name: ğŸ–¼ï¸ Format
        run: pnpm run format:check

      - name: ğŸ–ï¸ Build
        env:
          SKIP_ENV_VALIDATION: 1
        run: pnpm run build

      - name: ğŸ§ª Test
        run: pnpm run test:ci
