name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.SUPABASE_GITHUB_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.SUPABASE_GOOGLE_CLIENT_SECRET }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”¨ Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: âš¡ Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: ğŸ¬ Start Supabase
        run: pnpm run db:start:dev

      - name: ğŸ”„ Verify Supabase types are up to date
        run: |
          pnpm run db:generate
          if ! git diff --ignore-space-at-eol --exit-code --quiet packages/database/src/types/generated/schema.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: ğŸ–Œï¸ Format
        run: pnpm run format:check

      - name: ğŸ“¦ Build
        # builds only sync app, because we're building web in Next.js bundle analysis
        run: pnpm run build:sync

      - name: ğŸ›» Lint
        run: pnpm run lint

      - name: ğŸ§ª Test
        run: pnpm run test:ci
